name: Trigger Jenkins Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Debug URL (temporary)
        run: |
          echo "URL is: ${{ secrets.JENKINS_URL }}/job/Petclinic_testing/build"

      - name: Trigger Jenkins Job
        run: |
          curl -v -X POST \
            -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/job/Petclinic_testing/build"
